# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridges',
            old_name='idfridges',
            new_name='fridgesID',
        ),
    ]
