# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0003_auto_20160113_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridges',
            name='status',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
