# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-01 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0004_fridges_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fridges',
            old_name='fridgegroup',
            new_name='fridgeGroup',
        ),
        migrations.RenameField(
            model_name='fridges',
            old_name='situated',
            new_name='fridgeLocation',
        ),
        migrations.RenameField(
            model_name='fridges',
            old_name='status',
            new_name='fridgeStatus',
        ),
        migrations.RenameField(
            model_name='fridges',
            old_name='temperature',
            new_name='fridgeTemp',
        ),
    ]
