# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fridges', '0005_auto_20160301_0747'),
    ]

    operations = [
        migrations.CreateModel(
            name='fridgesdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fridgesdataTemp', models.IntegerField()),
                ('fridgesdataTime', models.DateTimeField()),
                ('fridgesdataID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fridges.fridges')),
            ],
        ),
    ]
